### ISSUE TITLE
Issue-Update trietest.txt

New proposed explanatory format

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#106]
Automated Review Comments
Issues in README.md:
  - (2, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in rlptest.txt:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in trietest.txt:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
