### ISSUE TITLE
Issue-Work in progress external test runner

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#110]
Automated Review Comments
Issues in README.md:
  - (4, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
Issues in db_query_interface.go:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in test_runner.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in test_runner_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (29, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
