### ISSUE TITLE
Issue-WIP rewrite vm

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#112]
Automated Review Comments
Issues in block.go:
  - (13, 'TODO found')
  - (14, 'TODO found')
  - (14, 'Line exceeds 80 characters')
  - (18, 'TODO found')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Line exceeds 80 characters')
  - (77, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
Issues in block_manager.go:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
  - (19, 'TODO found')
Issues in parsing.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in parsing_test.go:
  - (8, 'Hardcoded string found')
Issues in testing.go:
  - (2, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')
Issues in trie_test.go:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
Issues in vm.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in vm_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
