### ISSUE TITLE
Issue-Wip VM. Created contracts

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#114]
Automated Review Comments
Issues in block.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in block_manager.go:
  - (4, 'Line exceeds 80 characters')
  - (7, 'TODO found')
  - (9, 'TODO found')
Issues in transaction.go:
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
Issues in vm_test.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
