### ISSUE TITLE
Issue-Pop, push, load for vm

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#116]
Automated Review Comments
Issues in vm.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
Issues in vm_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (37, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
