### ISSUE TITLE
Issue-Parsing for block and tx

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#120]
Automated Review Comments
Issues in block.go:
  - (1, 'Line exceeds 80 characters')
Issues in parsing.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Line exceeds 80 characters')
Issues in transaction.go:
  - (1, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
