### ISSUE TITLE
Issue-Contract creation, updating and fee processing

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#124]
Automated Review Comments
Issues in block.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (41, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
