### ISSUE TITLE
Issue-Updated trie test

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#150]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
Issues in trietest.txt:
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (24, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
