### ISSUE TITLE
Issue-update trie algorithm

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#154]
Automated Review Comments
Issues in trietest.txt:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Line exceeds 80 characters')
  - (6, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
