### ISSUE TITLE
Issue-First dagger impl

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#156]
Automated Review Comments
Issues in README.md:
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (11, 'Line exceeds 80 characters')
Issues in dagger.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (23, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
