### ISSUE TITLE
Issue-WIP Block chain

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#164]
Automated Review Comments
Issues in block_manager.go:
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (42, 'TODO found')
  - (47, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
