### ISSUE TITLE
Issue-Minor update

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#166]
Automated Review Comments
Issues in ethereum.go:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
Issues in memory_database.go:
  - (5, 'Hardcoded string found')
Issues in server.go:
  - (2, 'Hardcoded string found')
Issues in testing.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in trie.go:
  - (14, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (31, 'Hardcoded string found')
Issues in util.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
