### ISSUE TITLE
Issue-db console is now a general console.

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#168]
Automated Review Comments
Issues in dagger.go:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in db_query_interface.go:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
Issues in ethereum.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
