### ISSUE TITLE
Issue-Dagger improvements

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#170]
Automated Review Comments
Issues in dagger.go:
  - (29, 'TODO found')
  - (37, 'Hardcoded string found')
Issues in dagger_test.go:
  - (5, 'Hardcoded string found')
  - (12, 'Line exceeds 80 characters')
Issues in ethereum.go:
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
Issues in vm_test.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
