### ISSUE TITLE
Issue-Peer handling

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#176]
Automated Review Comments
Issues in peer.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in server.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (22, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
