### ISSUE TITLE
Issue-Updated server and peers and mining processing

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#178]
Automated Review Comments
Issues in dagger.go:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (24, 'TODO found')
  - (33, 'Hardcoded string found')
Issues in ethereum.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
Issues in peer.go:
  - (17, 'Line exceeds 80 characters')
  - (76, 'TODO found')
Issues in server.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (55, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
