### ISSUE TITLE
Issue-WIP Splitting ethereum up in submodules

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#194]
Automated Review Comments
Issues in block.go:
  - (1, 'TODO found')
  - (1, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (22, 'TODO found')
  - (25, 'Line exceeds 80 characters')
  - (35, 'TODO found')
  - (37, 'Line exceeds 80 characters')
Issues in peer.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (58, 'Line exceeds 80 characters')
  - (74, 'TODO found')
  - (102, 'Line exceeds 80 characters')
  - (117, 'TODO found')

**Comment by scdnj** [comment]
I got it.
