### ISSUE TITLE
Issue-Moving the ethgo to individual packages

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#196]
Automated Review Comments
Issues in block_manager.go:
  - (4, 'Hardcoded string found')
  - (29, 'TODO found')
  - (34, 'Hardcoded string found')
  - (55, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
Issues in dagger.go:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in dev_console.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
Issues in ethereum.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
Issues in rlp.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
Issues in server.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
Issues in vm.go:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (72, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
