### ISSUE TITLE
Issue-gofmt no coding standards

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#198]
Automated Review Comments
Issues in block_manager.go:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (47, 'TODO found')
  - (52, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (74, 'TODO found')
  - (79, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (108, 'Line exceeds 80 characters')
  - (113, 'Line exceeds 80 characters')
  - (120, 'TODO found')
  - (134, 'Line exceeds 80 characters')
  - (141, 'TODO found')
Issues in dagger.go:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (64, 'TODO found')
  - (66, 'TODO found')
Issues in dagger_test.go:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in dev_console.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (58, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (75, 'Line exceeds 80 characters')
  - (116, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (133, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (144, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (155, 'Hardcoded string found')
  - (157, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (169, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
Issues in ethereum.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (129, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
Issues in peer.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (61, 'TODO found')
  - (79, 'TODO found')
  - (95, 'Line exceeds 80 characters')
  - (110, 'TODO found')
  - (126, 'TODO found')
Issues in rlp.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (140, 'Hardcoded string found')
  - (227, 'Line exceeds 80 characters')
  - (267, 'Line exceeds 80 characters')
  - (283, 'Line exceeds 80 characters')
  - (323, 'Line exceeds 80 characters')
  - (390, 'Hardcoded string found')
  - (454, 'Hardcoded string found')
Issues in rlp_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (59, 'Hardcoded string found')
  - (70, 'Hardcoded string found')
  - (73, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (89, 'Hardcoded string found')
Issues in server.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (148, 'Hardcoded string found')
  - (168, 'Hardcoded string found')
Issues in test_runner.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
Issues in test_runner_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
Issues in vm.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (429, 'Line exceeds 80 characters')
  - (486, 'Line exceeds 80 characters')
  - (493, 'Line exceeds 80 characters')

**Comment by Oyase-shinobi** [comment]
I got it.
