### ISSUE TITLE
Issue-Block verification, TD calculations and overall block processing

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#209]
Automated Review Comments
Issues in block_manager.go:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (55, 'TODO found')
  - (67, 'Hardcoded string found')
  - (70, 'Line exceeds 80 characters')
  - (88, 'Line exceeds 80 characters')
  - (109, 'TODO found')
  - (121, 'Line exceeds 80 characters')
  - (124, 'Hardcoded string found')
  - (145, 'TODO found')

**Comment by hitosisasaki** [comment]
I got it.
