### ISSUE TITLE
Issue-Rlp integer fix

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#211]
Automated Review Comments
Issues in block_manager.go:
  - (6, 'TODO found')
  - (23, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (42, 'TODO found')
  - (54, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (68, 'Line exceeds 80 characters')
  - (71, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
Issues in peer.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (38, 'Line exceeds 80 characters')
  - (46, 'TODO found')
  - (53, 'TODO found')
  - (56, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (90, 'Hardcoded string found')
  - (106, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
