### ISSUE TITLE
Issue-Server testing blocks

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#213]
Automated Review Comments
Issues in ethereum.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in server.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (104, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
