### ISSUE TITLE
Issue-Format

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#215]
Automated Review Comments
Issues in block_manager.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (17, 'TODO found')
  - (20, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (40, 'TODO found')
Issues in peer.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (27, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
