### ISSUE TITLE
Issue-Increased buffer size

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#219]
Automated Review Comments
Issues in peer.go:
  - (2, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (51, 'Hardcoded string found')
  - (68, 'Hardcoded string found')
Issues in server.go:
  - (18, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
