### ISSUE TITLE
Issue-Peer reaping and fake network

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#221]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
Issues in server.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (29, 'TODO found')
  - (49, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (58, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
