### ISSUE TITLE
Issue-Some miner reports

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#223]
Automated Review Comments
Issues in block_manager.go:
  - (1, 'Line exceeds 80 characters')
Issues in dagger.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
Issues in peer.go:
  - (5, 'Hardcoded string found')
Issues in server.go:
  - (10, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
