### ISSUE TITLE
Issue-Updated to temporary trie

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#225]
Automated Review Comments
Issues in dev_console.go:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (33, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
