### ISSUE TITLE
Issue-Updated tests

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#229]
Automated Review Comments
Issues in dagger_test.go:
  - (7, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
Issues in test_runner_test.go:
  - (4, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (27, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
