### ISSUE TITLE
Issue-Removed capitalization of the json source

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#235]
Automated Review Comments
Issues in test_runner_test.go:
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
