### ISSUE TITLE
Issue-Moved the vm code the block manager and added more opcodes

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#243]
Automated Review Comments
Issues in block_manager.go:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (27, 'TODO found')
  - (54, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (61, 'Line exceeds 80 characters')
  - (61, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (75, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (134, 'Line exceeds 80 characters')
  - (141, 'Line exceeds 80 characters')
  - (161, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
