### ISSUE TITLE
Issue-Added more opcodes

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#247]
Automated Review Comments
Issues in block_manager.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (48, 'TODO found')

**Comment by satokihanada** [comment]
I got it.
