### ISSUE TITLE
Issue-ECmul tmp

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#249]
Automated Review Comments
Issues in block_manager.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (34, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (59, 'Hardcoded string found')
  - (65, 'Line exceeds 80 characters')
  - (72, 'TODO found')
  - (88, 'TODO found')
Issues in block_manager_test.go:
  - (4, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
