### ISSUE TITLE
Issue-Updated the wire protocol

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#251]
Automated Review Comments
Issues in peer.go:
  - (24, 'Hardcoded string found')
  - (56, 'TODO found')
  - (67, 'TODO found')
  - (70, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (79, 'Line exceeds 80 characters')
  - (83, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (111, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
  - (117, 'Line exceeds 80 characters')
Issues in server.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
  - (32, 'TODO found')
  - (33, 'TODO found')
  - (43, 'Hardcoded string found')
  - (46, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
