### ISSUE TITLE
Issue-Added get peers and peers msg.

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#259]
Automated Review Comments
Issues in peer.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (23, 'TODO found')
  - (32, 'Line exceeds 80 characters')
  - (47, 'Line exceeds 80 characters')
  - (63, 'Hardcoded string found')
Issues in server.go:
  - (1, 'Line exceeds 80 characters')
  - (6, 'TODO found')
  - (18, 'TODO found')
  - (65, 'TODO found')

**Comment by Oyase-shinobi** [comment]
I got it.
