### ISSUE TITLE
Issue-Added synchronisation of transactions across remote pools

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#273]
Automated Review Comments
Issues in dev_console.go:
  - (22, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (37, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
Issues in ethereum.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (34, 'TODO found')
  - (34, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (40, 'Hardcoded string found')
  - (47, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (67, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (76, 'Hardcoded string found')
Issues in peer.go:
  - (9, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
Issues in transaction_pool.go:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (33, 'Line exceeds 80 characters')
  - (46, 'Line exceeds 80 characters')

**Comment by Zeusofsky** [comment]
I got it.
