### ISSUE TITLE
Issue-Rearrange packages

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#277]
Automated Review Comments
Issues in dev_console.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')
  - (47, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (34, 'TODO found')
  - (93, 'TODO found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (162, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (185, 'Hardcoded string found')
  - (194, 'Hardcoded string found')
  - (206, 'TODO found')
  - (206, 'Line exceeds 80 characters')
  - (208, 'Line exceeds 80 characters')
  - (210, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (247, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (252, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
