### ISSUE TITLE
Issue-Updated packages

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#279]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'TODO found')
  - (124, 'TODO found')
  - (153, 'TODO found')
  - (153, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (202, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (215, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
Issues in peer.go:
  - (8, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
