### ISSUE TITLE
Issue-Data send over the wire shouldn't be RLPed more then once

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#283]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (41, 'TODO found')
  - (124, 'TODO found')
  - (153, 'TODO found')
  - (153, 'Line exceeds 80 characters')
  - (155, 'Line exceeds 80 characters')
  - (157, 'Hardcoded string found')
  - (189, 'Line exceeds 80 characters')
  - (192, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (228, 'Hardcoded string found')
  - (229, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
Issues in peer.go:
  - (17, 'Line exceeds 80 characters')
  - (18, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
