### ISSUE TITLE
Issue-tx is now part of the chain package

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#285]
Automated Review Comments
Issues in dev_console.go:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (9, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (34, 'TODO found')
  - (93, 'TODO found')
  - (120, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (163, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (195, 'Hardcoded string found')
  - (207, 'TODO found')
  - (207, 'Line exceeds 80 characters')
  - (209, 'Line exceeds 80 characters')
  - (211, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (241, 'Hardcoded string found')
  - (248, 'Hardcoded string found')
  - (252, 'Hardcoded string found')
  - (253, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
