### ISSUE TITLE
Issue-Fake block mining

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#290]
Automated Review Comments
Issues in dev_console.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (39, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (61, 'Line exceeds 80 characters')
  - (62, 'Line exceeds 80 characters')
  - (66, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (77, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (37, 'TODO found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (102, 'TODO found')
  - (166, 'TODO found')
  - (166, 'Line exceeds 80 characters')
  - (168, 'Line exceeds 80 characters')
  - (170, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (197, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (219, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
