### ISSUE TITLE
Issue-Dev contracts

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#293]
Automated Review Comments
Issues in dev_console.go:
  - (1, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
