### ISSUE TITLE
Issue-Graceful shutdown of peers

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#300]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'TODO found')
  - (126, 'TODO found')
  - (155, 'TODO found')
  - (155, 'Line exceeds 80 characters')
  - (157, 'Line exceeds 80 characters')
  - (159, 'Hardcoded string found')
  - (191, 'Line exceeds 80 characters')
  - (194, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (216, 'Line exceeds 80 characters')
  - (219, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
Issues in peer.go:
  - (27, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')

**Comment by seriousfuzzy** [comment]
I got it.
