### ISSUE TITLE
Issue-Debugging handles

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#302]
Automated Review Comments
Issues in dev_console.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (11, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (36, 'TODO found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (115, 'TODO found')
  - (167, 'TODO found')
  - (167, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (171, 'Hardcoded string found')
  - (188, 'Line exceeds 80 characters')
  - (205, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (226, 'Line exceeds 80 characters')
  - (269, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
