### ISSUE TITLE
Issue-Removed default connection

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#304]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'TODO found')
  - (127, 'TODO found')
  - (146, 'TODO found')
  - (146, 'Line exceeds 80 characters')
  - (148, 'Line exceeds 80 characters')
  - (150, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (217, 'Hardcoded string found')
  - (219, 'Hardcoded string found')
  - (226, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
Issues in peer.go:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (24, 'Line exceeds 80 characters')
  - (26, 'TODO found')
  - (38, 'TODO found')

**Comment by hitosisasaki** [comment]
I got it.
