### ISSUE TITLE
Issue-Switched port and removed logging

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#306]
Automated Review Comments
Issues in ethereum.go:
  - (4, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (38, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
