### ISSUE TITLE
Issue-Implemented get chain msg

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#312]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (41, 'Hardcoded string found')
  - (43, 'TODO found')
  - (127, 'TODO found')
  - (141, 'TODO found')
  - (141, 'Line exceeds 80 characters')
  - (143, 'Line exceeds 80 characters')
  - (145, 'Hardcoded string found')
  - (194, 'Line exceeds 80 characters')
  - (198, 'Line exceeds 80 characters')
  - (214, 'Hardcoded string found')
  - (216, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (245, 'Hardcoded string found')
Issues in peer.go:
  - (11, 'TODO found')
  - (25, 'Line exceeds 80 characters')
  - (28, 'Hardcoded string found')
  - (49, 'Line exceeds 80 characters')
  - (51, 'TODO found')
  - (52, 'Line exceeds 80 characters')
  - (65, 'Line exceeds 80 characters')
  - (71, 'Line exceeds 80 characters')
  - (80, 'Line exceeds 80 characters')

**Comment by Oyase-shinobi** [comment]
I got it.
