### ISSUE TITLE
Issue-Self connect detect

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#324]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (36, 'TODO found')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (119, 'TODO found')
  - (157, 'TODO found')
  - (157, 'Line exceeds 80 characters')
  - (159, 'Line exceeds 80 characters')
  - (161, 'Hardcoded string found')
  - (196, 'Line exceeds 80 characters')
  - (203, 'Line exceeds 80 characters')
  - (212, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (233, 'Hardcoded string found')
  - (237, 'Line exceeds 80 characters')
Issues in peer.go:
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (37, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (78, 'Line exceeds 80 characters')
  - (81, 'Hardcoded string found')
  - (84, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
