### ISSUE TITLE
Issue-fix build failure

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#328]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (35, 'TODO found')
  - (81, 'Hardcoded string found')
  - (82, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (116, 'TODO found')
  - (183, 'TODO found')
  - (183, 'Line exceeds 80 characters')
  - (185, 'Line exceeds 80 characters')
  - (187, 'Hardcoded string found')
  - (208, 'Line exceeds 80 characters')
  - (222, 'Hardcoded string found')
  - (224, 'Hardcoded string found')
  - (231, 'Hardcoded string found')
  - (243, 'Line exceeds 80 characters')
  - (247, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
Issues in test_runner_test.go:
  - (8, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
