### ISSUE TITLE
Issue-Peer connection checking

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#330]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (36, 'TODO found')
  - (79, 'Hardcoded string found')
  - (80, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
  - (119, 'TODO found')
  - (160, 'TODO found')
  - (160, 'Line exceeds 80 characters')
  - (162, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (213, 'Line exceeds 80 characters')
  - (217, 'Line exceeds 80 characters')
  - (230, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (255, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
