### ISSUE TITLE
Issue-(un)pack addr

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#338]
Automated Review Comments
Issues in peer.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')
  - (114, 'Hardcoded string found')
  - (146, 'Line exceeds 80 characters')
  - (165, 'Hardcoded string found')
  - (167, 'Line exceeds 80 characters')
  - (169, 'Line exceeds 80 characters')
  - (172, 'Hardcoded string found')
  - (175, 'Line exceeds 80 characters')
  - (194, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
