### ISSUE TITLE
Issue-Update README

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#340]
Automated Review Comments
Issues in dev_console.go:
  - (1, 'Line exceeds 80 characters')
  - (18, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (44, 'Line exceeds 80 characters')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (37, 'TODO found')
  - (59, 'Hardcoded string found')
  - (60, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (116, 'TODO found')
  - (187, 'TODO found')
  - (187, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (228, 'Line exceeds 80 characters')
  - (233, 'Line exceeds 80 characters')
  - (249, 'Hardcoded string found')
  - (251, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
Issues in test_runner_test.go:
  - (8, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
