### ISSUE TITLE
Issue-UPNP wip

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#347]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (37, 'TODO found')
  - (92, 'Hardcoded string found')
  - (93, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (131, 'TODO found')
  - (187, 'TODO found')
  - (187, 'Line exceeds 80 characters')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (259, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (284, 'Line exceeds 80 characters')
  - (285, 'Hardcoded string found')
  - (296, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (313, 'Line exceeds 80 characters')
Issues in peer.go:
  - (11, 'Line exceeds 80 characters')
  - (60, 'Hardcoded string found')
Issues in upnp.go:
  - (22, 'Hardcoded string found')
  - (37, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (42, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (54, 'Hardcoded string found')
  - (56, 'Line exceeds 80 characters')
  - (138, 'Hardcoded string found')
  - (146, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (154, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (163, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (171, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (173, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (189, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (249, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (259, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (290, 'Line exceeds 80 characters')
  - (294, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (303, 'Hardcoded string found')
  - (304, 'Line exceeds 80 characters')
  - (304, 'Hardcoded string found')
  - (305, 'Hardcoded string found')
  - (307, 'Hardcoded string found')
  - (319, 'Hardcoded string found')
  - (334, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (341, 'Line exceeds 80 characters')
  - (342, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
  - (362, 'Line exceeds 80 characters')
  - (364, 'Line exceeds 80 characters')
  - (365, 'Line exceeds 80 characters')
  - (367, 'Line exceeds 80 characters')
  - (374, 'Hardcoded string found')
  - (379, 'TODO found')
  - (390, 'Line exceeds 80 characters')
  - (392, 'Line exceeds 80 characters')
  - (393, 'Line exceeds 80 characters')
  - (397, 'Hardcoded string found')
  - (402, 'TODO found')

**Comment by satomichru** [comment]
I got it.
