### ISSUE TITLE
Issue-RLP Updates

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#349]
Automated Review Comments
Issues in dev_console.go:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Line exceeds 80 characters')
Issues in ethereum.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (95, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (129, 'TODO found')
  - (139, 'Line exceeds 80 characters')
  - (200, 'TODO found')
  - (200, 'Line exceeds 80 characters')
  - (202, 'Line exceeds 80 characters')
  - (204, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (260, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (271, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (292, 'Line exceeds 80 characters')
  - (297, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (310, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
