### ISSUE TITLE
Issue-Updated rlp encoding. (requires verification!)

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#35]
Automated Review Comments
Issues in rlp.go:
  - (2, 'Hardcoded string found')
  - (104, 'Hardcoded string found')
Issues in rlp_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (17, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
