### ISSUE TITLE
Issue-Reverted back to messages

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#352]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (38, 'TODO found')
  - (93, 'Hardcoded string found')
  - (94, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (132, 'TODO found')
  - (137, 'Line exceeds 80 characters')
  - (189, 'TODO found')
  - (189, 'Line exceeds 80 characters')
  - (191, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (238, 'Line exceeds 80 characters')
  - (250, 'Line exceeds 80 characters')
  - (274, 'Line exceeds 80 characters')
  - (274, 'Hardcoded string found')
  - (285, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (316, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
