### ISSUE TITLE
Issue-upnp test

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#360]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (40, 'TODO found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (96, 'Line exceeds 80 characters')
  - (148, 'TODO found')
  - (200, 'Line exceeds 80 characters')
  - (264, 'Line exceeds 80 characters')
  - (292, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (355, 'Hardcoded string found')
Issues in peer.go:
  - (10, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')

**Comment by Oyase-shinobi** [comment]
I got it.
