### ISSUE TITLE
Issue-removed upnp

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#364]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (37, 'TODO found')
  - (102, 'TODO found')
  - (151, 'Hardcoded string found')
  - (152, 'Hardcoded string found')
  - (222, 'Line exceeds 80 characters')
  - (245, 'Hardcoded string found')
  - (253, 'Hardcoded string found')
  - (291, 'Line exceeds 80 characters')

**Comment by hitosisasaki** [comment]
I got it.
