### ISSUE TITLE
Issue-Implemented support for UPnP

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#366]
Automated Review Comments
Issues in ethereum.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (90, 'Line exceeds 80 characters')
  - (90, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (112, 'Hardcoded string found')
  - (115, 'Hardcoded string found')
Issues in nat.go:
  - (5, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Line exceeds 80 characters')
Issues in natpmp.go:
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'TODO found')
  - (35, 'Line exceeds 80 characters')
  - (41, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (52, 'Line exceeds 80 characters')
Issues in natupnp.go:
  - (8, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (101, 'Hardcoded string found')
  - (102, 'Hardcoded string found')
  - (109, 'Hardcoded string found')
  - (110, 'Hardcoded string found')
  - (117, 'Hardcoded string found')
  - (118, 'Hardcoded string found')
  - (125, 'Hardcoded string found')
  - (126, 'Hardcoded string found')
  - (127, 'Hardcoded string found')
  - (128, 'Hardcoded string found')
  - (135, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (144, 'Hardcoded string found')
  - (199, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (214, 'Hardcoded string found')
  - (231, 'Line exceeds 80 characters')
  - (234, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (241, 'Line exceeds 80 characters')
  - (241, 'Hardcoded string found')
  - (242, 'Hardcoded string found')
  - (244, 'Hardcoded string found')
  - (246, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (269, 'Line exceeds 80 characters')
  - (273, 'Hardcoded string found')
  - (278, 'TODO found')
  - (278, 'Line exceeds 80 characters')
  - (293, 'Line exceeds 80 characters')
  - (295, 'Line exceeds 80 characters')
  - (296, 'Line exceeds 80 characters')
  - (298, 'Line exceeds 80 characters')
  - (306, 'Hardcoded string found')
  - (311, 'TODO found')
  - (318, 'Line exceeds 80 characters')
  - (320, 'Line exceeds 80 characters')
  - (321, 'Line exceeds 80 characters')
  - (326, 'Hardcoded string found')
  - (331, 'TODO found')

**Comment by ishida0415** [comment]
I got it.
