### ISSUE TITLE
Issue-Implemented decoding rlp

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#37]
Automated Review Comments
Issues in rlp.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (47, 'Line exceeds 80 characters')
Issues in rlp_test.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
