### ISSUE TITLE
Issue-UPnP support

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#371]
Automated Review Comments
Issues in ethereum.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (77, 'Hardcoded string found')
  - (115, 'TODO found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (235, 'Line exceeds 80 characters')
  - (261, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (319, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (350, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (403, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
