### ISSUE TITLE
Issue-Disconnection reasons

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#375]
Automated Review Comments
Issues in peer.go:
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (50, 'Hardcoded string found')
  - (51, 'Hardcoded string found')
  - (52, 'Hardcoded string found')
  - (53, 'Hardcoded string found')
  - (87, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
