### ISSUE TITLE
Issue-Recipient as bytes

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#379]
Automated Review Comments
Issues in dev_console.go:
  - (2, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (14, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (15, 'Hardcoded string found')
  - (16, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
Issues in ethereum.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (77, 'Hardcoded string found')
  - (115, 'TODO found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (180, 'Hardcoded string found')
  - (235, 'Line exceeds 80 characters')
  - (261, 'Hardcoded string found')
  - (268, 'Hardcoded string found')
  - (319, 'Line exceeds 80 characters')
  - (350, 'Line exceeds 80 characters')
  - (350, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (403, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
