### ISSUE TITLE
Issue-removed self connect log

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#381]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (38, 'TODO found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (140, 'TODO found')
  - (251, 'Line exceeds 80 characters')
  - (273, 'Hardcoded string found')
  - (278, 'Hardcoded string found')
  - (315, 'Line exceeds 80 characters')
  - (354, 'Line exceeds 80 characters')
  - (354, 'Hardcoded string found')
  - (402, 'Hardcoded string found')
  - (405, 'Hardcoded string found')
Issues in peer.go:
  - (5, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
