### ISSUE TITLE
Issue-Changed mining

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#383]
Automated Review Comments
Issues in ethereum.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (36, 'TODO found')
  - (76, 'Hardcoded string found')
  - (114, 'TODO found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (179, 'Hardcoded string found')
  - (234, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (267, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (348, 'Hardcoded string found')
  - (397, 'Hardcoded string found')
  - (400, 'Hardcoded string found')

**Comment by satomichru** [comment]
I got it.
