### ISSUE TITLE
Issue-Do not quit if upnp fails

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#400]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (38, 'TODO found')
  - (63, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (65, 'Hardcoded string found')
  - (66, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (141, 'TODO found')
  - (242, 'Line exceeds 80 characters')
  - (262, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (336, 'Line exceeds 80 characters')
  - (359, 'Line exceeds 80 characters')
  - (359, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (386, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
