### ISSUE TITLE
Issue-Mining using a different hash now

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#402]
Automated Review Comments
Issues in ethereum.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (36, 'TODO found')
  - (76, 'Hardcoded string found')
  - (113, 'TODO found')
  - (175, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (178, 'Hardcoded string found')
  - (233, 'Line exceeds 80 characters')
  - (259, 'Hardcoded string found')
  - (266, 'Hardcoded string found')
  - (348, 'Line exceeds 80 characters')
  - (362, 'Hardcoded string found')
  - (365, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
