### ISSUE TITLE
Issue-Switched over to leveldb instead of memdb

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#408]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (38, 'TODO found')
  - (82, 'Hardcoded string found')
  - (120, 'TODO found')
  - (204, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (207, 'Hardcoded string found')
  - (208, 'Hardcoded string found')
  - (240, 'Line exceeds 80 characters')
  - (268, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (364, 'Line exceeds 80 characters')
  - (364, 'Hardcoded string found')
  - (374, 'Line exceeds 80 characters')
  - (392, 'Hardcoded string found')
  - (395, 'Hardcoded string found')
Issues in peer.go:
  - (2, 'Hardcoded string found')
  - (41, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
