### ISSUE TITLE
Issue-Added key address and key generation

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#412]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (5, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (10, 'Line exceeds 80 characters')
  - (16, 'Line exceeds 80 characters')
Issues in config.go:
  - (5, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
Issues in dev_console.go:
  - (4, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
Issues in ethereum.go:
  - (8, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (36, 'TODO found')
  - (90, 'Hardcoded string found')
  - (122, 'Hardcoded string found')
  - (124, 'Hardcoded string found')
  - (135, 'TODO found')
  - (137, 'Hardcoded string found')
  - (210, 'Line exceeds 80 characters')
  - (223, 'Hardcoded string found')
  - (254, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (276, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (372, 'Line exceeds 80 characters')
  - (372, 'Hardcoded string found')
  - (387, 'Line exceeds 80 characters')
  - (400, 'Hardcoded string found')
  - (403, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
