### ISSUE TITLE
Issue-Fixed self connect through public key discovery.

Bumped protocol version number

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#430]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (45, 'TODO found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (128, 'Line exceeds 80 characters')
  - (128, 'Hardcoded string found')
  - (140, 'TODO found')
  - (173, 'Line exceeds 80 characters')
  - (179, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (258, 'Line exceeds 80 characters')
  - (278, 'Hardcoded string found')
  - (284, 'Hardcoded string found')
  - (343, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (378, 'Hardcoded string found')
  - (388, 'Line exceeds 80 characters')
  - (405, 'Hardcoded string found')
  - (408, 'Hardcoded string found')
Issues in peer.go:
  - (5, 'Hardcoded string found')
  - (18, 'Line exceeds 80 characters')
  - (22, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (58, 'Line exceeds 80 characters')
  - (59, 'Line exceeds 80 characters')
  - (64, 'Line exceeds 80 characters')
  - (72, 'Hardcoded string found')
  - (74, 'Hardcoded string found')
  - (113, 'Hardcoded string found')
  - (116, 'Hardcoded string found')
  - (124, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
