### ISSUE TITLE
Issue-Added pub key to keyring

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#432]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (35, 'TODO found')
  - (89, 'Hardcoded string found')
  - (121, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (135, 'TODO found')
  - (161, 'Hardcoded string found')
  - (214, 'Line exceeds 80 characters')
  - (227, 'Hardcoded string found')
  - (258, 'Line exceeds 80 characters')
  - (260, 'Hardcoded string found')
  - (280, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (348, 'Hardcoded string found')
  - (378, 'Line exceeds 80 characters')
  - (378, 'Hardcoded string found')
  - (393, 'Line exceeds 80 characters')
  - (406, 'Hardcoded string found')
  - (409, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
