### ISSUE TITLE
Issue-Self connect on handshake

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#434]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (45, 'TODO found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (143, 'TODO found')
  - (176, 'Line exceeds 80 characters')
  - (182, 'Hardcoded string found')
  - (206, 'Hardcoded string found')
  - (261, 'Line exceeds 80 characters')
  - (281, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (346, 'Hardcoded string found')
  - (381, 'Line exceeds 80 characters')
  - (381, 'Hardcoded string found')
  - (391, 'Line exceeds 80 characters')
  - (408, 'Hardcoded string found')
  - (411, 'Hardcoded string found')
Issues in peer.go:
  - (1, 'Line exceeds 80 characters')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (38, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')

**Comment by Zeusofsky** [comment]
I got it.
