### ISSUE TITLE
Issue-Version 3 and added added catch up

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#436]
Automated Review Comments
Issues in peer.go:
  - (59, 'Hardcoded string found')
  - (64, 'Hardcoded string found')
  - (66, 'Line exceeds 80 characters')
  - (70, 'Hardcoded string found')
  - (76, 'Line exceeds 80 characters')
  - (82, 'Line exceeds 80 characters')
  - (85, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
