### ISSUE TITLE
Issue-Removed slice appending for integers

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#44]
Automated Review Comments
Issues in rlp.go:
  - (14, 'Line exceeds 80 characters')
  - (15, 'Line exceeds 80 characters')
Issues in rlp_test.go:
  - (3, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (16, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
