### ISSUE TITLE
Issue-Added some loggers

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#444]
Automated Review Comments
Issues in peer.go:
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (26, 'Line exceeds 80 characters')
  - (49, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (66, 'Line exceeds 80 characters')
  - (69, 'Line exceeds 80 characters')
  - (70, 'Line exceeds 80 characters')

**Comment by PhantomFortune** [comment]
I got it.
