### ISSUE TITLE
Issue-Changed client id

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#448]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (45, 'TODO found')
  - (82, 'Hardcoded string found')
  - (84, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (130, 'Hardcoded string found')
  - (142, 'TODO found')
  - (175, 'Line exceeds 80 characters')
  - (181, 'Hardcoded string found')
  - (205, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (280, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (380, 'Line exceeds 80 characters')
  - (380, 'Hardcoded string found')
  - (390, 'Line exceeds 80 characters')
  - (407, 'Hardcoded string found')
  - (410, 'Hardcoded string found')
Issues in peer.go:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (19, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
