### ISSUE TITLE
Issue-Seed bootstrapping added

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#461]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (47, 'TODO found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (100, 'Hardcoded string found')
  - (108, 'Hardcoded string found')
  - (151, 'TODO found')
  - (157, 'Line exceeds 80 characters')
  - (164, 'Hardcoded string found')
  - (239, 'Hardcoded string found')
  - (261, 'Line exceeds 80 characters')
  - (282, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (361, 'Hardcoded string found')
  - (396, 'Line exceeds 80 characters')
  - (396, 'Hardcoded string found')
  - (406, 'Line exceeds 80 characters')
  - (423, 'Hardcoded string found')
  - (426, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
