### ISSUE TITLE
Issue-Use seed

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#463]
Automated Review Comments
Issues in config.go:
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (91, 'Hardcoded string found')
  - (131, 'TODO found')
  - (136, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (248, 'Line exceeds 80 characters')
  - (251, 'Line exceeds 80 characters')
  - (256, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (281, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (363, 'Hardcoded string found')
  - (393, 'Line exceeds 80 characters')
  - (393, 'Hardcoded string found')
  - (408, 'Line exceeds 80 characters')
  - (421, 'Hardcoded string found')
  - (424, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
