### ISSUE TITLE
Issue-Interop!

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#465]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (47, 'TODO found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (144, 'TODO found')
  - (177, 'Line exceeds 80 characters')
  - (183, 'Hardcoded string found')
  - (259, 'Line exceeds 80 characters')
  - (265, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (399, 'Line exceeds 80 characters')
  - (399, 'Hardcoded string found')
  - (409, 'Line exceeds 80 characters')
  - (426, 'Hardcoded string found')
  - (429, 'Hardcoded string found')
Issues in peer.go:
  - (11, 'Line exceeds 80 characters')

**Comment by ishida0415** [comment]
I got it.
