### ISSUE TITLE
Issue-Default to .ethereum

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#469]
Automated Review Comments
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (91, 'Hardcoded string found')
  - (130, 'TODO found')
  - (139, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (249, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (367, 'Hardcoded string found')
  - (397, 'Line exceeds 80 characters')
  - (397, 'Hardcoded string found')
  - (412, 'Line exceeds 80 characters')
  - (425, 'Hardcoded string found')
  - (428, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
