### ISSUE TITLE
Issue-Refactoring RlpValue => Value

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#471]
Automated Review Comments
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (47, 'TODO found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (144, 'TODO found')
  - (178, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (266, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (428, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
Issues in peer.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (25, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (40, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')
  - (80, 'Hardcoded string found')
  - (85, 'TODO found')
  - (93, 'Line exceeds 80 characters')
  - (107, 'Line exceeds 80 characters')
  - (137, 'Line exceeds 80 characters')
  - (138, 'Line exceeds 80 characters')
  - (147, 'Line exceeds 80 characters')
  - (149, 'Line exceeds 80 characters')
  - (153, 'TODO found')
  - (163, 'Hardcoded string found')
  - (166, 'Line exceeds 80 characters')
  - (196, 'Hardcoded string found')
  - (200, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (225, 'Hardcoded string found')
  - (232, 'Hardcoded string found')
  - (234, 'Hardcoded string found')
  - (238, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (244, 'Line exceeds 80 characters')
  - (246, 'Line exceeds 80 characters')

**Comment by scdnj** [comment]
I got it.
