### ISSUE TITLE
Issue-Updated to the great merge package

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#479]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (75, 'Hardcoded string found')
Issues in dev_console.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (91, 'Hardcoded string found')
  - (130, 'TODO found')
  - (139, 'Hardcoded string found')
  - (141, 'Hardcoded string found')
  - (162, 'Hardcoded string found')
  - (249, 'Line exceeds 80 characters')
  - (252, 'Line exceeds 80 characters')
  - (257, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (288, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (398, 'Line exceeds 80 characters')
  - (398, 'Hardcoded string found')
  - (413, 'Line exceeds 80 characters')
  - (426, 'Hardcoded string found')
  - (429, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
