### ISSUE TITLE
Issue-Removed RlpValue in favour of Value

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#481]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
Issues in ethchain/block.go:
  - (15, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
Issues in ethchain/block_chain.go:
  - (1, 'Line exceeds 80 characters')
Issues in ethchain/block_manager.go:
  - (5, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (47, 'TODO found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (144, 'TODO found')
  - (178, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (266, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (428, 'Hardcoded string found')
  - (431, 'Hardcoded string found')
Issues in ethutil/rlp.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (21, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (153, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
Issues in ethutil/trie.go:
  - (32, 'Hardcoded string found')
  - (43, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
