### ISSUE TITLE
Issue-Added git flow explanation

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#487]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (47, 'TODO found')
  - (84, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (98, 'Hardcoded string found')
  - (132, 'Hardcoded string found')
  - (144, 'TODO found')
  - (178, 'Line exceeds 80 characters')
  - (184, 'Hardcoded string found')
  - (260, 'Line exceeds 80 characters')
  - (266, 'Hardcoded string found')
  - (283, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (366, 'Hardcoded string found')
  - (401, 'Line exceeds 80 characters')
  - (401, 'Hardcoded string found')
  - (411, 'Line exceeds 80 characters')
  - (428, 'Hardcoded string found')
  - (431, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
