### ISSUE TITLE
Issue-Removed debug message

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#503]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (74, 'Hardcoded string found')
Issues in ethereum.go:
  - (6, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (47, 'TODO found')
  - (84, 'Hardcoded string found')
  - (99, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (150, 'TODO found')
  - (187, 'Line exceeds 80 characters')
  - (193, 'Hardcoded string found')
  - (217, 'Hardcoded string found')
  - (272, 'Line exceeds 80 characters')
  - (292, 'Hardcoded string found')
  - (298, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (365, 'Hardcoded string found')
  - (410, 'Line exceeds 80 characters')
  - (410, 'Hardcoded string found')
  - (420, 'Line exceeds 80 characters')
  - (437, 'Hardcoded string found')
  - (440, 'Hardcoded string found')

**Comment by Zeusofsky** [comment]
I got it.
