### ISSUE TITLE
Issue-Added link to dev package

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#515]
Automated Review Comments
Issues in README.md:
  - (3, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (26, 'Line exceeds 80 characters')
  - (28, 'Line exceeds 80 characters')
  - (29, 'Line exceeds 80 characters')
  - (30, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')
  - (78, 'Hardcoded string found')
Issues in ethereum.go:
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (37, 'TODO found')
  - (91, 'Hardcoded string found')
  - (123, 'Hardcoded string found')
  - (141, 'TODO found')
  - (171, 'Hardcoded string found')
  - (258, 'Line exceeds 80 characters')
  - (261, 'Line exceeds 80 characters')
  - (266, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (291, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (320, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (407, 'Line exceeds 80 characters')
  - (407, 'Hardcoded string found')
  - (422, 'Line exceeds 80 characters')
  - (435, 'Hardcoded string found')
  - (438, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
