### ISSUE TITLE
Issue-Added dirty tracking on the cache

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#527]
Automated Review Comments
Issues in ethutil/trie.go:
  - (25, 'Hardcoded string found')
Issues in ethutil/trie_test.go:
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by scdnj** [comment]
I got it.
