### ISSUE TITLE
Issue-adding compact decode tests

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#537]
Automated Review Comments
Issues in ethutil/encoding_test.go:
  - (2, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
Issues in ethutil/trie.go:
  - (32, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
