### ISSUE TITLE
Issue-(un)marshal blocks and transactions

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#54]
Automated Review Comments
Issues in block.go:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (24, 'TODO found')
  - (30, 'Hardcoded string found')
  - (40, 'Line exceeds 80 characters')

**Comment by Oyase-shinobi** [comment]
I got it.
