### ISSUE TITLE
Issue-Comments

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#57]
Automated Review Comments
Issues in block.go:
  - (22, 'TODO found')
  - (25, 'TODO found')
  - (25, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
Issues in block_manager.go:
  - (5, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
