### ISSUE TITLE
Issue-Encoding helpers with tests

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#59]
Automated Review Comments
Issues in encoding.go:
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
Issues in encoding_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')

**Comment by PhantomFortune** [comment]
I got it.
