### ISSUE TITLE
Issue-Updated serialisation

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#63]
Automated Review Comments
Issues in block.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (32, 'TODO found')
  - (33, 'TODO found')
  - (37, 'TODO found')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Hardcoded string found')
  - (62, 'TODO found')
  - (64, 'Line exceeds 80 characters')

**Comment by satomichru** [comment]
I got it.
