### ISSUE TITLE
Issue-Split up db and trie and added interface

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#71]
Automated Review Comments
Issues in database.go:
  - (2, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
Issues in database_test.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (43, 'Hardcoded string found')
Issues in trie.test.go:
  - (5, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (40, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (46, 'Hardcoded string found')
  - (49, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (60, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
