### ISSUE TITLE
Issue-Added first three tests

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#75]
Automated Review Comments
Issues in rlp_test.go:
  - (11, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in rlptest.txt:
  - (4, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (32, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (48, 'Hardcoded string found')
Issues in trietest.txt:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by hitosisasaki** [comment]
I got it.
