### ISSUE TITLE
Issue-Fixed tests a bit

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#79]
Automated Review Comments
Issues in rlptest.txt:
  - (4, 'Line exceeds 80 characters')
  - (6, 'Line exceeds 80 characters')
Issues in trietest.txt:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by ishida0415** [comment]
I got it.
