### ISSUE TITLE
Issue-Working Trie

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#81]
Automated Review Comments
Issues in rlp_test.go:
  - (11, 'Hardcoded string found')
  - (14, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
Issues in trie.go:
  - (5, 'Hardcoded string found')
  - (57, 'Line exceeds 80 characters')
  - (57, 'Hardcoded string found')
  - (83, 'Hardcoded string found')
  - (139, 'Hardcoded string found')
  - (155, 'Hardcoded string found')
  - (159, 'Hardcoded string found')
  - (196, 'Line exceeds 80 characters')
Issues in trie_test.go:
  - (5, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
  - (39, 'Hardcoded string found')
  - (44, 'Hardcoded string found')
  - (45, 'Hardcoded string found')
  - (48, 'Hardcoded string found')
  - (57, 'Hardcoded string found')
  - (61, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (63, 'Hardcoded string found')
  - (67, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
