### ISSUE TITLE
Issue-Added db query interface and moved memory database

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#91]
Automated Review Comments
Issues in db_query_interface.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
  - (36, 'Hardcoded string found')
  - (42, 'Line exceeds 80 characters')
  - (69, 'Hardcoded string found')
  - (73, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (91, 'Hardcoded string found')
Issues in memory_database.go:
  - (8, 'Line exceeds 80 characters')
Issues in testing.go:
  - (5, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (36, 'Hardcoded string found')

**Comment by Oyase-shinobi** [comment]
I got it.
