### ISSUE TITLE
Issue-Moved some testing code

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/block-validation#94]
Automated Review Comments
Issues in ethereum.go:
  - (2, 'Hardcoded string found')
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (52, 'Hardcoded string found')

**Comment by seriousfuzzy** [comment]
I got it.
